# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import isilon_pb2 as isilon__pb2


class IsilonStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Info = channel.unary_unary(
        '/server.Isilon/Info',
        request_serializer=isilon__pb2.InfoRequest.SerializeToString,
        response_deserializer=isilon__pb2.InfoResponse.FromString,
        )


class IsilonServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Info(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IsilonServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Info': grpc.unary_unary_rpc_method_handler(
          servicer.Info,
          request_deserializer=isilon__pb2.InfoRequest.FromString,
          response_serializer=isilon__pb2.InfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'server.Isilon', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
