// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: isilon.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Server {
  public static partial class Isilon
  {
    static readonly string __ServiceName = "server.Isilon";

    static readonly grpc::Marshaller<global::Server.InfoRequest> __Marshaller_server_InfoRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Server.InfoRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Server.InfoResponse> __Marshaller_server_InfoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Server.InfoResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Server.InfoRequest, global::Server.InfoResponse> __Method_Info = new grpc::Method<global::Server.InfoRequest, global::Server.InfoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Info",
        __Marshaller_server_InfoRequest,
        __Marshaller_server_InfoResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Server.IsilonReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Isilon</summary>
    public abstract partial class IsilonBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Server.InfoResponse> Info(global::Server.InfoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Isilon</summary>
    public partial class IsilonClient : grpc::ClientBase<IsilonClient>
    {
      /// <summary>Creates a new client for Isilon</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IsilonClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Isilon that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IsilonClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IsilonClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IsilonClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Server.InfoResponse Info(global::Server.InfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Info(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Server.InfoResponse Info(global::Server.InfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Info, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Server.InfoResponse> InfoAsync(global::Server.InfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Server.InfoResponse> InfoAsync(global::Server.InfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Info, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IsilonClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IsilonClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(IsilonBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Info, serviceImpl.Info).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, IsilonBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Info, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Server.InfoRequest, global::Server.InfoResponse>(serviceImpl.Info));
    }

  }
}
#endregion
